apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-management-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DB_NAME: "reservation_management"
  DB_HOST: "reservation-db.default.svc.cluster.local"
  POSTGRES_DB: "reservation_management"

  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "postgres"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-reservation-management
  labels:
    app: app
    service: reservation-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      service: reservation-management
  template:
    metadata:
      labels:
        app: app
        service: reservation-management
    spec:
      containers:
      - name: app-reservation-management
        image: tinnaung/fjtn-co-working-reservation-management:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: reservation-management-config

---

apiVersion: v1
kind: Service
metadata:
  name: app-reservation-management
spec:
  selector:
    app: app
    service: reservation-management
  ports:
    - port: 3030        
      targetPort: 3030  
