apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
              name: pgadmin-port
          envFrom:
            - configMapRef: 
                name: pgadmin-config

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - name: pgadmin-port
      port: 5050
      targetPort: 80
  type: LoadBalancer
