apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-config
data:
  RABBITMQ_HOST: "rabbitMQ.default.svc.cluster.local"
  MONGO_HOST: "mongo.default.svc.cluster.local"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-report-service
  labels:
    app: app
    service: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      service: report-service
  template:
    metadata:
      labels:
        app: app
        service: report-service
    spec:
      containers:
      - name: app-report-service
        image: tinnaung/fjtn-report-service:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: report-service-config

---

apiVersion: v1
kind: Service
metadata:
  name: app-space-management
spec:
  selector:
    app: app
    service: space-management
  ports:
    - port: 3021        
      targetPort: 3021 