apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DB_NAME: "user_management"
  DB_HOST: "user-db.default.svc.cluster.local"
  POSTGRES_DB: "user_management"

  PGADMIN_USER: "admin@admin.com"

  FRONTEND_URL: "http://localhost:3000"
  STAFF_VERIFY_PATH: "/staff/verifyEmailReceive"
  USER_VERIFY_PATH: "/user/verifyEmailReceive"

  JWT_SECRET: "secret"
  JWT_TTL: "86400"

  MAILER_HOST: "smtp.gmail.com"
  MAILER_PORT: "587"
  MAILER_EMAIL: "username@gmail.com"
  MAILER_PASSWORD: "password"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-user-management
  labels:
    app: app
    service: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      service: user-management
  template:
    metadata:
      labels:
        app: app
        service: user-management
    spec:
      containers:
        - name: app-user-management
          image: tinnaung/fjtn-user-management:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-management-config

---
apiVersion: v1
kind: Service
metadata:
  name: app-user-management
spec:
  type: LoadBalancer
  selector:
    app: app
    service: user-management
  ports:
    - port: 3020
      targetPort: 3020
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: db-user-management
#   labels:
#     app: db
#     service: user-management
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: db
#       service: user-management
#   template:
#     metadata:
#       labels:
#         app: db
#         service: user-management
#     spec:
#       containers:
#         - name: init-db
#           image: postgres:12
#           envFrom:
#             - configMapRef:
#                 name: user-management-config
#           ports:
#             - containerPort: 5432
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: db-user-management
# spec:
#   type: ClusterIP
#   selector:
#     app: db
#     service: user-management
#   ports:
#     - port: 5432
#       targetPort: 5432

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: app-user-management
# spec:
#   type: LoadBalancer
#   selector:
#     app: app
#     service: user-management
#   ports:
#     - port: 3020
#       targetPort: 3020
